pantallas/apps/academics/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from .views import IndexAcademics

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pantallas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    
    url(r'^academicos/$',IndexAcademics.as_view(),name='academics'),
)

pantallas/apps/careers/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from .views import IndexCareer

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pantallas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

 
    url(r'^carreras/$',IndexCareer.as_view(),name='carreras')
)

pantallas/apps/events/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from .views import EventIndex

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pantallas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    
    
    url(r'^eventos/$',EventIndex.as_view(),name='index')
)

pantallas/apps/home/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from .views import IndexView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pantallas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', IndexView.as_view(),name='home'),
)

pantallas/pantallas/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pantallas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^',include('apps.home.urls',namespace='home')),
    url(r'^',include('apps.careers.urls',namespace='careers')),
    url(r'^',include('apps.vacancies.urls',namespace='vacancies')),
    url(r'^',include('apps.gripbox.urls',namespace='gripbox')),
    url(r'^',include('apps.events.urls',namespace='events')),
    url(r'^',include('apps.academics.urls',namespace='academics')),
    url(r'^admin/', include(admin.site.urls)),
  
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pantallas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head> 
	{% load static from staticfiles %} 
	<meta charset="utf-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
	<meta name="description" content="Creative One Page Parallax Template">
	<meta name="keywords" content="Creative, Onepage, Parallax, HTML5, Bootstrap, Popular, custom, personal, portfolio" /> 
	<meta name="author" content=""> 
	<title>{% block title %}{% endblock %}</title>
	
	
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet"> 
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet"> 
	<link href="{% static 'css/animate.css' %}" rel="stylesheet"> 
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet"> 
	<!--[if lt IE 9]> <script src="js/html5shiv.js"></script> 
	<script src="js/respond.min.js"></script> <![endif]--> 
	<!--<link rel="shortcut icon" href="images/ico/favicon.png"> 
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png"> 
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png"> 
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png"> 
	<link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">-->
</head><!--/head-->
<body>
	<div class="preloader">
		<div class="preloder-wrap">
			<div class="preloder-inner"> 
				<div class="ball"></div> 
				<div class="ball"></div> 
				<div class="ball"></div> 
				<div class="ball"></div> 
				<div class="ball"></div> 
				<div class="ball"></div> 
				<div class="ball"></div>
			</div>
		</div>
	</div><!--/.preloader-->
	<header id="navigation"> 
		{% block navbar %} {% endblock %}
	</header> <!--/#navigation--> 

	{% block content %}	{% endblock %}

	

	<footer id="footer"> 
		<div class="container"> 
			<div class="text-center"> 
				<p>Copyright &copy; 2016 - <a href="http://mostafiz.me/">Universidad Politécnica del Valle de Toluca</a> | All Rights Reserved</p> 
			</div> 
		</div> 
	</footer> <!--/#footer--> 

	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script> 
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/smoothscroll.js' %}"></script> 
	<script type="text/javascript" src="{% static 'js/jquery.isotope.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.prettyPhoto.js' %}"></script> 
	<script type="text/javascript" src="{% static 'js/jquery.parallax.js'%}"></script> 
	<script type="text/javascript" src="{% static 'js/main.js'%}"></script> 
</body>
</html>

pantallas/templates/bolsa.html
{%extends 'base.html'%}
{% load static from staticfiles %} 
{% block navbar %}
	<div class="navbar navbar-inverse navbar-fixed-top" role="banner"> 
		<div class="container"> 
			<div class="navbar-header"> 
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> 
					<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> 
				</button> 
				<a class="navbar-brand" href="#"><h1><img src="{% static 'images/gob.jpg' %}" alt="logo"></h1></a> 
				


			</div> 
			<div class="collapse navbar-collapse"> 
				<ul class="nav navbar-nav navbar-right"> 
					<li class="scroll"><a href="{% url 'home:home' %}">Inicio</a></li> 
					<li class="scroll"><a href="{% url 'careers:carreras' %}">Carreras</a></li> 
					<li class="scroll"><a href="{% url 'academics:academics' %}">Academicos</a></li> 
					<li class="scroll active"><a href="{% url 'vacancies:index'%}">Empleos</a></li> 
					<li class="scroll"><a href="{% url 'events:index'%}">Eventos</a></li> 
					<li class="scroll"><a href="{% url 'gripbox:index'%}">Buzon de sugerencias</a></li> 
					
				</ul> 
				<img style="margin-top: 15px;" src="{% static 'images/Logo.jpg' %}" alt="Logo.jpg">
			</div>
		</div> 

	</div><!--/navbar--> 

{% endblock %}
{% block content %}

	<section class="blog-header section-padding"><!-- blog-header -->
	  <div class="container"><!-- container -->
	    <div class="row"><!-- row -->
	      <div class="col-xs-12"><!-- col-xs-12 -->
	        <h1 class="section-title text-center">Bolsa de trabajo</h1>
	      </div><!-- /.col-xs-12 -->
	    </div><!-- /.row -->
	  </div><!-- /.container -->
	</section><!-- /.blog-header -->
	<section id="blog"> 
		<div class="container">
			<div class="row text-center clearfix">
				<div class="col-sm-8 col-sm-offset-2">
					<h4>Selecciona la carrera: </h4>
					    <form  action="{% url 'vacancies:index'%}" method="POST">
					      {% csrf_token %}
					         
					            
					               {{form}}
					                <button type="submit" class="btn btn-default" aria-label="Left Align">
					                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
					                </button>
					                
					                           	                                 
					  </form>
				</div>
			</div> 
			</form>
			</br>
			
			{% for vacancy in vacancies %}
				<div class="row">
					<div class="col-sm-12">
						<div class="single-blog">
							
							<h2>{{vacancy.company}}</h2>
							<ul class="post-meta">
								<li><i class="fa fa-pencil-square-o"></i><strong> Carrera:</strong>{{vacancy.career}}</li>
								<li><i class="fa fa-clock-o"></i><strong> Fecha:</strong>{{vacancy.pubDate}}</li>
							</ul>
							<div class="blog-content">
								<p>{{vacancy.description}}</p>
							</div>

							{% if vacancy.pdf.url != None  %}
							<a href="{{vacancy.pdf.url}}" class="btn btn-primary" data-toggle="modal" data-target="#blog-detail">Enviar a correo</a>
							{% endif %}
						</div>
					</div>		
				</div> 
			{% endfor %}
		</div> 
		</section> <!--/#blog-->		
		<div class="row text-center clearfix">
			<div class="col-sm-8 col-sm-offset-2">		
				  <nav>
				    <ul class="pagination">
				  	{% if vacancies.has_previous %}
				  	<li>
				  	  <a href="?page={{ vacancies.previous_page_number }}" aria-label="Previous">
				  	    <span aria-hidden="true">&laquo;</span>
				  	  </a>
				  	</li>
				  	{% endif %}
				  	
				  	{% for _ in vacancies.paginator.page_range %}
				  		
				  		{% if vacancies.number == forloop.counter %}	
				  			<li class="active"><a href="?page={{forloop.counter}}">{{forloop.counter}}<span class="sr-only">(current)</span></a></li>
				  			{%else%}
				  			<li><a href="?page={{forloop.counter}}">{{forloop.counter}}<span class="sr-only">(current)</span></a></li>
				  		{% endif %}
				  	{% endfor %}

				  	{% if vacancies.has_next%}
				  	<li>
				  	  <a href="?page={{ vacancies.next_page_number }}" aria-label="Next">
				  	    <span aria-hidden="true">&raquo;</span>
				  	  </a>
				  	</li>
				  	{% endif %}
				    </ul>
				  </nav>
			</div>
		</div> 
		
{% endblock %}

					

	<footer id="footer"> 
		<div class="container"> 
			<div class="text-center"> 
				<p>Copyright &copy; 2016 - <a href="http://mostafiz.me/">Universidad Politécnica del Valle de Toluca</a> | All Rights Reserved</p> 
			</div> 
		</div> 
	</footer> <!--/#footer--> 

	<script type="text/javascript" src="js/jquery.js"></script> 
	<script type="text/javascript" src="js/bootstrap.min.js"></script>
	<script type="text/javascript" src="js/smoothscroll.js"></script> 
	<script type="text/javascript" src="js/jquery.isotope.min.js"></script>
	<script type="text/javascript" src="js/jquery.prettyPhoto.js"></script> 
	<script type="text/javascript" src="js/jquery.parallax.js"></script> 
	<script type="text/javascript" src="js/main.js"></script> 
</body>
</html>

pantallas/templates/buzon.html
{%extends 'base.html'%}
{%load static from staticfiles%}
{%block title%}UPVT{%endblock%}
{% block navbar %}
	<div class="navbar navbar-inverse navbar-fixed-top" role="banner"> 
		<div class="container"> 
			<div class="navbar-header"> 
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> 
					<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> 
				</button> 
				<a class="navbar-brand" href="#"><h1><img src="{% static 'images/gob.jpg' %}" alt="logo"></h1></a> 
				


			</div> 
			<div class="collapse navbar-collapse"> 
				<ul class="nav navbar-nav navbar-right"> 
					<li class="scroll active"><a href="{% url 'home:home' %}">Inicio</a></li> 
					<li class="scroll"><a href="{% url 'careers:carreras' %}">Carreras</a></li> 
					<li class="scroll"><a href="{% url 'academics:academics' %}">Academicos</a></li> 
					<li class="scroll"><a href="{% url 'vacancies:index'%}">Empleos</a></li> 
					<li class="scroll"><a href="{% url 'events:index'%}">Eventos</a></li> 
					<li class="scroll"><a href="{% url 'gripbox:index'%}">Buzon de sugerencias</a></li> 
					
				</ul> 
				<img style="margin-top: 15px;" src="{% static 'images/Logo.jpg' %}" alt="Logo.jpg">
			</div>
		</div> 

	</div><!--/navbar--> 

{% endblock %}

{% block content %}
</br>
<section id="contact">
	<div class="container">
		<div class="row text-center clearfix">
			<div class="col-sm-8 col-sm-offset-2">
				<div class="contact-heading">
					<h2 class="title-one">Buzon de sugerencias</h2>
					<p>El buzón de sugerencias y quejas son instrumentos puestos a disposición de los miembros de la comunidad universitaria  para hacernos llegar las observaciones y reclamaciones que estimen convenientes sobre el funcionamiento, así como para la mejora de la calidad de los servicios.</p>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="contact-details">
			<div class="pattern"></div>
			<div class="row text-center clearfix">
				
				<div class="col-sm-12"> 
					<div id="contact-form-section">
						<div class="status alert alert-success" style="display: none"></div>
						<form id="contact-form" class="contact" name="contact-form" method="post" action="{% url 'gripbox:index'%}">
						{% csrf_token %}
							<div class="form-group">
								{{form.name}}
								<div class="form-group">
								{{form.email}}
								</div> 
								<div class="form-group">
								{{form.comentario}}
								</div> 
								<div class="form-group">
									<button type="submit" class="btn btn-primary">Enviar</button>
								</div>
							</form> 
						</div>
					</div>
				</div>
			</div>
		</div> 
	</section> <!--/#contact--> 


{% endblock %}		

	

pantallas/templates/eventos.html
{% extends 'base.html'%}
{% load static from staticfiles %}

{% block navbar %}
<div class="navbar navbar-inverse navbar-fixed-top" role="banner"> 
		<div class="container"> 
			<div class="navbar-header"> 
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> 
					<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> 
				</button> 
				<a class="navbar-brand" href="#"><h1><img src="{% static 'images/gob.jpg' %}" alt="logo"></h1></a> 
				


			</div> 
			<div class="collapse navbar-collapse"> 
				<ul class="nav navbar-nav navbar-right"> 
					<li class="scroll"><a href="{% url 'home:home' %}">Inicio</a></li> 
					<li class="scroll"><a href="{% url 'careers:carreras' %}">Carreras</a></li> 
					<li class="scroll"><a href="{% url 'academics:academics' %}">Academicos</a></li> 
					<li class="scroll"><a href="{% url 'vacancies:index'%}">Empleos</a></li> 
					<li class="scroll active"><a href="{% url 'events:index'%}">Eventos</a></li> 
					<li class="scroll"><a href="{% url 'gripbox:index'%}">Buzon de sugerencias</a></li> 
					
				</ul> 
				<img style="margin-top: 15px;" src="{% static 'images/Logo.jpg' %}" alt="Logo.jpg">
			</div>
		</div> 

	</div><!--/navbar--> 

{% endblock %}
{%block content%}
</br>	
<section id="blog"> 
	<div class="container">
		<div class="row text-center clearfix">
			<div class="col-sm-8 col-sm-offset-2">
				<h2 class="title-one">Eventos y avisos</h2>
				<p class="blog-heading">Mantente actualizado con las notificaciones de la escuela.</p>
			</div>
		</div> 
		<div class="row">
			{% for event in events %}
			<div class="col-sm-4">
				<div class="single-blog">
					<img src="{{event.img.url}}" alt="" />
					<h2>{{event.title}}</h2>
					<ul class="post-meta">
						
						<li><i class="fa fa-clock-o"></i><strong> Fecha:</strong> {{event.pub_date}}</li>
					</ul>
					<div class="blog-content">
						<p>{{event.description}}</p>
					</div>
					<a href="" class="btn btn-primary" data-toggle="modal" data-target="#blog-detail">Leer Mas</a>
				</div>
				<div class="modal fade" id="blog-detail" tabindex="-1" role="dialog" aria-hidden="true">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-body">
								<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
								<img src="{{event.img.url}}" alt="" />
								<h2>{{event.title}}</h2>
								<p>{{event.description}}</p>
							</div> 
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
			</div> 
		</div> 
	</section> <!--/#blog-->

	<div class="row text-center clearfix"> <!-- paginator-->
		<div class="col-sm-8 col-sm-offset-2">		
			  <nav> 
			    <ul class="pagination">
			  	{% if events.has_previous %}
			  	<li>
			  	  <a href="?page={{ events.previous_page_number }}" aria-label="Previous">
			  	    <span aria-hidden="true">&laquo;</span>
			  	  </a>
			  	</li>
			  	{% endif %}
			  	
			  	{% for _ in events.paginator.page_range %}
			  		
			  		{% if events.number == forloop.counter %}	
			  			<li class="active"><a href="?page={{forloop.counter}}">{{forloop.counter}}<span class="sr-only">(current)</span></a></li>
			  			{%else%}
			  			<li><a href="?page={{forloop.counter}}">{{forloop.counter}}<span class="sr-only">(current)</span></a></li>
			  		{% endif %}
			  	{% endfor %}

			  	{% if events.has_next%}
			  	<li>
			  	  <a href="?page={{ events.next_page_number }}" aria-label="Next">
			  	    <span aria-hidden="true">&raquo;</span>
			  	  </a>
			  	</li>
			  	{% endif %}
			    </ul>
			  </nav>
		</div>
	</div><!-- #/paginator--> 
{%endblock%}

pantallas/templates/index.html
{%extends 'base.html'%}
{% load static from staticfiles %} 
{% block title %}UPVT{% endblock%}
{% block navbar %}
	<div class="navbar navbar-inverse navbar-fixed-top" role="banner"> 
		<div class="container"> 
			<div class="navbar-header"> 
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> 
					<span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> 
				</button> 
				<a class="navbar-brand" href="#"><h1><img src="{% static 'images/gob.jpg' %}" alt="logo"></h1></a> 
				


			</div> 
			<div class="collapse navbar-collapse"> 
				<ul class="nav navbar-nav navbar-right"> 
					<li class="scroll active"><a href="{% url 'home:home' %}">Inicio</a></li> 
					<li class="scroll"><a href="{% url 'careers:carreras' %}">Carreras</a></li> 
					<li class="scroll"><a href="{% url 'academics:academics' %}">Academicos</a></li> 
					<li class="scroll"><a href="{% url 'vacancies:index'%}">Empleos</a></li> 
					<li class="scroll"><a href="{% url 'events:index'%}">Eventos</a></li> 
					<li class="scroll"><a href="{% url 'gripbox:index'%}">Buzon de sugerencias</a></li> 
					
				</ul> 
				<img style="margin-top: 15px;" src="{% static 'images/Logo.jpg' %}" alt="Logo.jpg">
			</div>
		</div> 

	</div><!--/navbar--> 

{% endblock %}
{% block content%}


	<section id="home">
		<div class="home-pattern"></div>
		<div id="main-carousel" class="carousel slide" data-ride="carousel"> 
			<ol class="carousel-indicators">
			
				{% for _ in slides %}
					{% if forloop.counter0 == 0 %}
				    <li data-target="#main-carousel" data-slide-to="0" class="active"></li>
				    {% else %}
				    <li data-target="#main-carousel" data-slide-to="{{forloop.counter0}}"></li>
				   	{% endif %}

					
				{% endfor %}

			</ol><!--/.carousel-indicators--> 
			<div class="carousel-inner">


			{% for slide in slides %}
				{% if forloop.counter0 == 0 %}
				<div class="item active" style="background-image: url({{slide.docfile.url}})"> 
						<div class="carousel-caption"> <div> 
							<h2 class="heading animated bounceInDown">{{slide.name}}</h2> 
								<p class="animated bounceInUp">{{slide.description}}</p> 
								<a class="btn btn-default slider-btn animated fadeIn" href="{{slide.link}}">Enlase</a>  
						</div> 
					</div> 
				</div> 
				{% else %}
				<div class="item" style="background-image: url({{slide.docfile.url}})"> 
						<div class="carousel-caption"> <div> 
							<h2 class="heading animated bounceInDown">{{slide.name}}</h2> 
								<p class="animated bounceInUp">{{slide.description}}</p> 
								<a class="btn btn-default slider-btn animated fadeIn" href="{{slide.link}}">Enlase</a>  
						</div> 
					</div> 
				</div> 
				{% endif %}
			{% endfor %}
			
		</div><!--/.carousel-inner-->

		<a class="carousel-left member-carousel-control hidden-xs" href="#main-carousel" data-slide="prev"><i class="fa fa-angle-left"></i></a>
		<a class="carousel-right member-carousel-control hidden-xs" href="#main-carousel" data-slide="next"><i class="fa fa-angle-right"></i></a>
	</div> 

</section><!--/#home-->

<section id="about-us">
	<div class="container">
		<div class="text-center">
			<div class="col-sm-8 col-sm-offset-2">
				<h2 class="title-one">UNIVERSIDAD POLITÉCNICA DEL VALLE DE TOLUCA</h2>
			</div>
		</div>
		<div class="about-us">
			<div class="row">
				<div class="col-sm-6">
					<h3>Nuestros valores</h3>
					<ul class="nav nav-tabs">
						<li><a href="#mission" data-toggle="tab"><i class="fa fa-th-large"></i> Mision</a></li>
						<li><a href="#vision" data-toggle="tab"><i class="fa fa-th-large"></i> Vision 2020</a></li>
						<li><a href="#valores" data-toggle="tab"><i class="fa fa-users"></i> Valores</a></li>
					</ul>
					<div class="tab-content">
						<div class="tab-pane fade in active" id="about">
							<div class="media">
							<!--	<img class="pull-left media-object" src="images/about-us/about.jpg" alt="about us"> -->
								<div class="media-body">
									<p>Contribuir al desarrollo tecnológico nacional mediante la formación de profesionistas y postgraduados en investigación y desarrollo tecnológico, y la prestación de servicios de actualización y solución de problemas    técnicos a los sectores público y privado, en un marco de valores que considere primordialmente el desarrollo humano y la preservación del medio ambiente.</p>
								</div>
							</div>
						</div>
						<div class="tab-pane fade" id="mission">
							<div class="media">
								<!--<img class="pull-left media-object" src="images/about-us/mission.jpg" alt="Mission"> -->
								<div class="media-body">
									<p>Contribuir al desarrollo nacional mediante la formación de profesionistas y postgraduados en investigación y desarrollo tecnológico, y la presentación de servicios de actualización y solución de problemas técnicos a los sectores públicos y privados, en un marco de valores que considere primordialmente el desarrollo humano y la preservación.</p>
								</div>
							</div>
						</div>
						<div class="tab-pane fade" id="vision">
							<div class="media">
								<!--<img class="pull-left media-object" src="images/about-us/mission.jpg" alt="Mission"> -->
								<div class="media-body">
									<p>Ser una Institución de Educación Superior con programas educativos de calidad, que cumple con las expectativas de   la comunidad universitaria, el sector productivo y la sociedad; con egresados competitivos, integrados al ámbito   laboral en su disciplina y con capacidades para el autoempleo; también cuenta con una planta académica certificada   y comprometida; reconocida por el impulso a la ciencia e investigación, así como los servicios tecnológicos y de educación continua que ofrece; mediante sistemas consolidados y certificados, logrando impacto social sobre nuestro    entorno a través  de la equidad, los valores  y actitudes positivas de la comunidad UPVT. </p>
								</div>
							</div>
						</div>
						<div class="tab-pane fade" id="valores">
							<div class="media">
								<!--<img class="pull-left media-object" src="images/about-us/community.jpg" alt="Community"> -->
								<div class="media-body">
									<b>Compromiso: </b>
									<p>establecerse metas, asumir la responsabilidad de su cumplimiento y lograr los objetivos en tiempo y forma</p>
									<b>Respeto: </b>
									<p>considerar las opiniones y puntos de vista de los demás desde un enfoque de tolerancia y trato digno. Aceptar las diferencias económicas, culturales, de raza, físicas e ideológicas.</p>
									<b>Honestidad: </b>
									<p>actura con apego a la verdad y sujetarse a trasparencia, teniendo como norma congruencia entre pensar, sentir y actuar.</p>
									<b>Justicia: </b>
									<p>darle a cada individuo lo que le corresponde, mediante el establecimiento de reglas que permitan evaluar un acto.</p>
									<b>Trabajo en equipo: </b>
									<p>sinergia de ezfuerzos y capacidades de un grupo de trabajo, para el logro de objetivos y metas en común.</p>
									<b>Sustentabilidad: </b>
									<p>respeto y preservación del medio ambiente y toda forma de vida.</p>
									<b>Excelencia: </b>
									<p>logro de los objetivos, superando las expectativas en cuanto a ejecución y resultados.</p>
									<b>Equidad: </b>
									<p>Permitir la igualdad de partcipación de hombres y mujeres en las actividades universitarias, permitiéndoles gozar de sus derechos, desarrollar sus talentos y habilidades, y proyectandolos hacia la sociedad en general.</p>

								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<h3>Video Institucional</h3>
					<div class="skill-bar">
						
						   
						     <video controls="controls" width="90%" >
						       <source src="{%static 'video/UPVT.mp4' %}" type="video/mp4" />
						     </video>
												
					</div> <!-- End Skill Bar -->
				</div>
			</div>
				</div>
			</div>
		</div>
	</section><!--/#about-us-->
	<section id="mexiquense">
		<div class="container">
			<div class="about-us">
				<div class="row">

					<div class="col-sm-6">
						
						<div class="skill-bar">
							
							   
							<video controls="controls" width="90%" >
							  <source src="{%static 'video/MEXIQUENSE.mp4'%}" type="video/mp4" />
							</video>
													
						</div> <!-- End Skill Bar -->
					</div>
					<div class="col-sm-6">
						<h3>Soy mexiquense</h3>
						<p>Este es un tributo a las bellezas naturales, arquitectónicas, a la cultura y a la gente del Estado de México; gente que nació aquí o en otro lugar, pero que aquí tienen su hogar; gente que ha puesto su trabajo, que ha puesto su talento y su empeño para construir este gran estado que hoy te presentamos y que nos hace decir con orgullo: Yo Soy Mexiquense.</p>
						
					</div>
				</div>
					</div>
				</div>
			</div>
		</section><!--/#about-mexiqueense-->
	

{% endblock %}	